#!/usr/bin/env python3
"""Write plugins/rftools_kicad/calculators.json from the rfhub monorepo.

The plugin maps a stackup to calculator inputs by key, unit and bound. Those
live in the monorepo, generated from the frontend calculator registry:

    backend/src/data/calculator_catalog.json     input keys, units, defaults
    backend/src/data/calculator_provenance.json  the stated bounds (what the
                                                 API's provenance and its
                                                 solve call read) and the
                                                 formula reference
    backend/src/core/calculators/                the API's own calculators, run
                                                 once at their defaults to list
                                                 the output keys /calculate
                                                 returns

This script copies what the plugin uses, for the calculators it uses, into a
small file committed with the plugin, so the plugin never needs the
monorepo. tests/test_calculators.py re-extracts and compares when the
monorepo is present, and skips in a standalone clone.

    python3 scripts/extract_calculators.py           # rewrite the file
    python3 scripts/extract_calculators.py --check   # exit 1 if it is stale
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
MONOREPO = ROOT.parent
BACKEND_SRC = MONOREPO / "backend" / "src"
CATALOG = BACKEND_SRC / "data" / "calculator_catalog.json"
PROVENANCE = BACKEND_SRC / "data" / "calculator_provenance.json"
DEST = ROOT / "plugins" / "rftools_kicad" / "calculators.json"

#: Every calculator the plugin calls (design Decision 2), in a fixed order.
SLUGS = (
    "microstrip-impedance",
    "controlled-impedance",
    "asymmetric-stripline",
    "coplanar-waveguide",
    "differential-pair",
    "edge-coupled-internal-symmetric",
    "edge-coupled-internal-asymmetric",
    "trace-width-current",
    "via-calculator",
)


class ExtractError(RuntimeError):
    pass


def monorepo_present() -> bool:
    return CATALOG.is_file() and PROVENANCE.is_file() and BACKEND_SRC.is_dir()


def _output_keys(slug: str, defaults: dict) -> list:
    """The keys the API's calculator returns in ``values``, in its order."""
    if str(BACKEND_SRC) not in sys.path:
        sys.path.insert(0, str(BACKEND_SRC))
    from core.calculators.registry import ALL_CALCULATORS  # type: ignore[import-not-found]

    result = ALL_CALCULATORS[slug](dict(defaults))
    values = result.get("values") or {}
    if not values:
        raise ExtractError(f"{slug} returned no values at its defaults: {result.get('errors')}")
    return list(values)


def extract() -> dict:
    catalog = {entry["slug"]: entry for entry in json.loads(CATALOG.read_text(encoding="utf-8"))}
    provenance = json.loads(PROVENANCE.read_text(encoding="utf-8"))["calculators"]
    calculators = {}
    for slug in SLUGS:
        if slug not in catalog or slug not in provenance:
            raise ExtractError(f"{slug} is missing from the catalogue or the provenance file")
        entry, prov = catalog[slug], provenance[slug]
        inputs = []
        for field in entry["inputs"]:
            key = field["key"]
            bound = prov["bounds"].get(key) or {}
            # The catalogue and the provenance file are generated from the same
            # registry; a disagreement means one of them is stale.
            for side in ("min", "max"):
                if field.get(side) != bound.get(side):
                    raise ExtractError(
                        f"{slug}.{key}: catalogue {side} {field.get(side)!r} != "
                        f"provenance {side} {bound.get(side)!r}"
                    )
            inputs.append({
                "key": key,
                "unit": field.get("unit", ""),
                "default": field["defaultValue"],
                "min": bound.get("min"),
                "max": bound.get("max"),
            })
        defaults = {field["key"]: field["default"] for field in inputs}
        calculators[slug] = {
            "title": entry["title"],
            "inputs": inputs,
            "outputs": _output_keys(slug, defaults),
            "formulaRef": prov.get("formulaRef"),
        }
    return {
        "$comment": (
            "GENERATED by scripts/extract_calculators.py from the rfhub monorepo's "
            "calculator catalogue, provenance file and API calculators. Do not edit."
        ),
        "calculators": calculators,
    }


def render(data: dict) -> str:
    return json.dumps(data, indent=2, ensure_ascii=False) + "\n"


def main(argv=None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--check", action="store_true", help="compare, do not write")
    args = parser.parse_args(argv)
    if not monorepo_present():
        print(f"The monorepo's calculator files are not at {BACKEND_SRC}.", file=sys.stderr)
        return 1
    text = render(extract())
    if args.check:
        if not DEST.is_file() or DEST.read_text(encoding="utf-8") != text:
            print(f"{DEST.relative_to(ROOT)} is stale; run scripts/extract_calculators.py",
                  file=sys.stderr)
            return 1
        return 0
    DEST.write_text(text, encoding="utf-8")
    print(f"wrote {DEST.relative_to(ROOT)} ({len(SLUGS)} calculators)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
